### ISSUE TITLE
Refactor related-table tests to use create root

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#105]
**Is your feature request related to a problem? Please describe.**
`ReactDOM.render` is no longer supported in react 18, but is utilized in the related table tests.

This causes the following warning
```
 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```
**Describe the solution you'd like**
Follow guide https://reactjs.org/link/switch-to-createroot

**Comment by square-li** [comment]
fixed by https://github.com/awslabs/iot-app-kit/pull/151

**Comment by sheilaXu** [comment]
This fix is reverted in https://github.com/awslabs/iot-app-kit/pull/150 because it's incompatible with react v17 and we want to continue with v17 for the reason mentioned in the PR.
