### ISSUE TITLE
@iot-app-kit/components live mode is broken

### ISSUE THREAD

**Issue by NorbertNader** [awslabs/iot-app-kit#107]
**Describe the bug**
The data is being requested but the viewport stops scrolling after a few minutes.

**To Reproduce**
1. Change the duration in testing ground to 10 minutes 
https://github.com/awslabs/iot-app-kit/blob/main/packages/components/src/testing/testing-ground/testing-ground.tsx#L61
https://github.com/awslabs/iot-app-kit/blob/main/packages/components/src/testing/testing-ground/testing-ground.tsx#L75
2. Update the asset and property ids for the queries, e.g. use SiteWise Demo Assets for a steady stream of data
3. Start the server `yarn start`
4. The viewport will freeze after a few minutes

**Expected behavior**
The viewport scrolls to current time

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: chrome
 - Version: 101.0.4951.64

**Comment by diehbria** [comment]
Fixed issue in https://github.com/awslabs/synchro-charts/pull/144

I found the issue - which stemmed in SynchroCharts. This issue occurred when the amount of data within a chart which utilized the `webgl-base` component (i.e. line chart, scatter chart, bar chart, and status-timeline components), when the buffer filled and it needed to create a large newer buffer to pass data into webgl, it would incorrectly register the new chart in a way that made live mode fail. Once the synchro charts fix I've made is in, this issue will be resolved.
