### ISSUE TITLE
Module not found: Error: Can't resolve in node_modules/@iot-app-kit/scene-composer/

### ISSUE THREAD

**Issue by fidel-tensoriot** [awslabs/iot-app-kit#1100]
**Describe the bug**
When trying to create a Twinmaker scene I get a bunch of node module errors from the following line of code. 
`import { SceneViewer } from '@iot-app-kit/scene-composer';`

**To Reproduce**
0. Have a react app through create-react-app
1. Install the following packages `@iot-app-kit/source-iottwinmaker`, `@aws-sdk/client-iottwinmaker`
2. Use the packages above to initialize a connection to twinmaker 
```     const sceneLoader = initialize('workspace', { client }).s3SceneLoader('scene') ```
3. Add the `@iot-app-kit/scene-composer`  and try to use ` <SceneViewer sceneLoader={sceneLoader}/>`

**Expected behavior**
To be able to use Twinmake Scene Viewer

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chome and Firefox

<img width="1680" alt="Screen Shot 2023-05-08 at 3 33 18 PM" src="https://user-images.githubusercontent.com/97477304/236952325-c0d1828f-e5b6-49ce-b049-7ce0a3b56a1d.png">

**Comment by TheEvilDev** [comment]
If I'm reading your steps to reproduce, can you confirm you've also installed the `@iot-app-kit/scene-composer` package?

There's 2 in appkit:
- source-iottwinmaker -> This is if you want to use a data source powered by TwinMaker API
- scene-composer -> this is the actual visualization component for TwinMaker Scenes

**Comment by TheEvilDev** [comment]
Actually read your screenshot, this react-intl issue, which version of '@iot-app-kit/scene-composer' are you using? This was an issue in previous versions of v5, but should not be in the latest builds.

**Comment by fidel-tensoriot** [comment]
I got the following from this command
```npm i @iot-app-kit/source-iottwinmaker @aws-sdk/client-iottwinmaker @iot-app-kit/scene-composer --legacy-peer-deps```

        "@aws-sdk/client-iottwinmaker": "^3.329.0",
        "@iot-app-kit/scene-composer": "^3.2.0",
        "@iot-app-kit/source-iottwinmaker": "^5.7.0",

But wondering is the preferred method to use `npm i` on scene composer and source-iottwinmaker or something  I noticed looking into the documentation for the individual component it says deprecated Link below. 

https://github.com/awslabs/iot-app-kit/blob/main/docs/SceneViewer.md

Im trying to add a scene from twinmaker into my react app and was following this . https://awslabs.github.io/iot-app-kit/?path=/docs/components-sceneviewer--docs

**Comment by rohitkvasanth** [comment]
I'm using react 18, however, can't install @iot-app-kit/scene-composer.
tried the above steps without using --legacy-peer-deps, getting the below error.
<img width="832" alt="Screenshot 2023-05-30 at 6 16 16 PM" src="https://github.com/awslabs/iot-app-kit/assets/96172954/a861d3a0-8733-4b2c-8b7e-d2426eddc4d5">

I tried modifying the react version to 17, but then the iot-app-kit libraries are throwing errors basically expecting react 18 features.

**Comment by haweston** [comment]
Resolved in latest version
