### ISSUE TITLE
resource explorer missing css styles

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#113]
**Describe the bug**
Resource explorer component styles aren't being included as expected in the libraries exported `styles.css` file

Below is a screen shot of the incorrect styling:
![Screen Shot 2022-05-20 at 12 49 03 PM](https://user-images.githubusercontent.com/77755322/169601342-c36bf00e-67b8-4f5f-9aa7-884c277ce772.png)

**To Reproduce**
Utilize `iot-resource-explorer`, does not display as expected. An example utilization of iot-app-kit with this occuring is within https://gitlab.aws.dev/proserve-es/awesome-sitewise-applications/amplify-iot-app-kit-demo

**Comment by tjuranek** [comment]
Upon investigation I'm not able to reproduce this bug. 

I attempted to replicate the issue in the linked repository but I wasn't able to get it building. I created a new demo application to test the `<ResourceExplorer />` component with. When running `iot-app-kit` locally or running my demo app the component is styled correctly. 

The styles are properly applied in the current latest version of app kit, `v1.5.0`, but I also tried the `v1.3.0` version specified in the linked repository but still could not replicate the issue.

![Screen Shot 2022-08-09 at 9 58 41 AM](https://user-images.githubusercontent.com/12429401/183689141-8e84999d-59d2-4d7f-b706-aae913dad889.png)

**Comment by diehbria** [comment]
Could you share the example code used in attempt to recreate the issue @tjuranek

**Comment by tjuranek** [comment]
I made a `create-react-app` project and followed the [getting started docs](https://github.com/awslabs/iot-app-kit/blob/main/docs/GettingStarted.md). I tried to replicate with different versions of app kit, as well as implementing the styles with a css `@import` like shown in the linked demo repository.

```js
import { ResourceExplorer, WebglContext } from '@iot-app-kit/react-components';
import { initialize } from '@iot-app-kit/source-iotsitewise';
import { useState, useEffect } from 'react';
import "@iot-app-kit/components/styles.css";


function App() {
  const [query, setQuery] = useState(null);

  useEffect(() => {
    setQuery(initialize({
      awsCredentials: {
        accessKeyId: "",
        secretAccessKey: "",
        sessionToken: "",
      },
      awsRegion: 'us-west-2',
      settings: { 
        batchDuration: undefined,
        legacyAPI: false,
      }
    }).query);
  }, []);

  return (
    <>
      <h2>Test App</h2>

      <div style={{ width: '300px', margin: '1rem' }}>
        <ResourceExplorer
          query={query?.assetTree.fromRoot()}
          onSelectionChange={(event) => console.log(event)}
          columnDefinitions={[{
            sortingField: 'name',
            id: 'name',
            header: 'Asset Name',
            cell: ({ name }) => name
          }]}
        />
      </div>

      <WebglContext />
    </>
  );
}

export default App;
```

**Comment by diehbria** [comment]
will reopen if were given a reproducible example
