### ISSUE TITLE
Data incorrectly pushed to series-connector

### ISSUE THREAD

**Issue by janezhang10** [awslabs/iot-app-kit#153]
**Describe the bug**
Data is being pushed upon every Live tick to `iot-time-series-connector` when in Live mode. The `prevDataCache` for `hasRequestedInformationChanged()` is sometimes undefined, which causes `hasRequestedInformationChanged` to always return true.

**To Reproduce**
1. Have a working testing-ground with working assetIds
2. Produce a time series chart with duration '1m' (preferably line chart so that the data is aggregated compared to scatter)
3. Have some console logs in `hasRequestedInformationChanged` that details `prevDataStreamStore`
4. Run the App Kit locally and inspect the page
5. See that `prevDataStreamStore` is occasionally undefined in console

**Expected behavior**
Only new incoming data should be pushed to `iot-time-series-connector` in Live mode. `hasRequestedInformationChanged` should only return true if there's new incoming data that needs to be rendered, and `prevDataCache` should only be undefined upon initialization of `DataCache`.

**Screenshots**
example of `prevDataStreamStore` being undefined while `currDataStreamStore` is defined after letting App Kit run locally for a while.
<img width="487" alt="Screen Shot 2022-07-08 at 3 59 35 PM" src="https://user-images.githubusercontent.com/40257222/178080002-3f0cff93-2a6d-45d7-bd62-dc3c232d5b79.png">
<img width="1067" alt="Screen Shot 2022-07-08 at 4 00 38 PM" src="https://user-images.githubusercontent.com/40257222/178080078-6406075d-3935-4a4f-a70a-24eaa9dd6d28.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser Firefox
 - Version 91.10.0esr

**Additional context**
The frequency of `prevDataCache` being undefined depends on the duration of the viewport. The smaller the duration (e.g. 1 minute), the more often `prevDataCache` is undefined (about every other tick).

**Comment by NorbertNader** [comment]
This issue no longer exists in latest version.
