### ISSUE TITLE
Update table widget - fix the table column width adjustment issue - duplicate of #1870

### ISSUE THREAD

**Issue by mnischay** [awslabs/iot-app-kit#1859]
### Details
in edit mode the user is not able to adjust the width of individual columns

### Acceptance criteria

- [ ] the user should be easily able to move the wdith adjuster
- [ ] when the user tries to adjust the width of the column of the table, the overall chart should not move

https://github.com/awslabs/iot-app-kit/assets/135036199/eb3245e7-4813-479e-836e-a173afef9218

**Comment by diehbria** [comment]
issue resolved
