### ISSUE TITLE
Update table widget - Make the column resizable in the table

### ISSUE THREAD

**Issue by nadeswal** [awslabs/iot-app-kit#1870]
Current- state: The user cannot resize the columns of the table instead the table widget moves across the canvas when the user tries to resize the column.

Preferred UX: Please follow as much guidelines provided by cloudscape for table widget. 
Link for how the interaction and design guidelines for resizing the column: [https://cloudscape.design/components/table/?tabId=playground&example=resizable-columns](url)

Please note: We don't need filter or search box in the table. However, pagination will be needed.
refer to https://github.com/awslabs/iot-app-kit/issues/1859 for a demo video

**Comment by diehbria** [comment]
issue resolved
