### ISSUE TITLE
Update table widget - Add fixed height and width for the table widget

### ISSUE THREAD

**Issue by nadeswal** [awslabs/iot-app-kit#1872]
Current state: When a user adds a table widget, the table is barely visible and the third column is hidden because of it's size. The outline of the table widget is bigger than then the table inside it and that needs to be fixed.

Preferred UX: The table widget should have a fixed width: 100px and height: 60 px  when the use drag and drops the widget. i.e initial size (we can play with the size and pick one that suits better) that is filled throughout it's selection boundaries. 

Let's use the empty state design provided by the cloudscape. Link: [https://cloudscape.design/components/table/?tabId=playground&example=empty-state](url) Again, let's not add search box.

Change the "no resource" text to "No data to display"
Change the "create resource" text in the button to "add asset properties"

**Comment by diehbria** [comment]
issue has been resolved
