### ISSUE TITLE
Update table widget - Table interaction in relation to the properties

### ISSUE THREAD

**Issue by nadeswal** [awslabs/iot-app-kit#1873]
Current state: The user has to expand the size of the widget to see their property and the bottom border of the table disappear.

Preferred UX: The table widget should expand from an empty state until the 10th property and that's when the scroll hits in for more than 10 properties but less than 100. 

Let's play around the min number of properties in the initial fixed size of table as mentioned in the previous task. (Maybe 5)

**Comment by diehbria** [comment]
issue has been resolved
