### ISSUE TITLE
Scene in <SceneViewer> appear only in one color

### ISSUE THREAD

**Issue by sagIoTPower** [awslabs/iot-app-kit#1914]
I build a component using [SceneViewer](https://github.com/awslabs/iot-app-kit/blob/main/docs/SceneViewer.md).
When I render my model of a wind turbine, it only appears in **one** single color **white**.

![Cumulocity_Windmill](https://github.com/awslabs/iot-app-kit/assets/29702059/12976e7d-e051-4891-8fd1-90493a9441f5)

When I render the [CookieFactoryMixer.glb](https://github.com/aws-samples/aws-iot-twinmaker-samples/blob/main/src/workspaces/cookiefactory/scenes/CookieFactoryMixer.glb) with my component, it appears in several colors.

The model of a turbine shows in the scene compose in AWS TwinMaker in several colors.

How do I have to transform my model of a wind turbine to render it the same way as in AWS TwinMaker Composer?

Regards Christof

**Comment by haweston** [comment]
Since the mixer model works are you able to share your wind turbine file for us to test a solution with?

**Comment by sheilaXu** [comment]
@sagIoTPower can you check the version of those 3d related dependencies in your package-lock.json (or yarn.lock) to see if they are the same as ours?
```
    "@react-three/drei": "9.56.27",
    "@react-three/fiber": "^8.13.3",
    "@react-three/postprocessing": "2.6.2",
    "three": "0.151.3",
    "three-mesh-bvh": "0.5.24",
    "three-stdlib": "2.23.9",
```

**Comment by sagIoTPower** [comment]
@sheilaXu : These are exactly the versions I use.
I updated my project to use these versions of the iot-app-kit version.
And now it works and I can view the wind-turbine with all the details.

**Comment by sheilaXu** [comment]
> @sheilaXu : These are exactly the versions I use. I updated my project to use these versions of the iot-app-kit version. And now it works and I can view the wind-turbine with all the details.

Great! I'll close this issue as resolved then.
