### ISSUE TITLE
Accessibility - WCAG 2.1 AA Compliance

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#1916]
Parent ticket to track all discovered accessibility issues.

```[tasklist]
### Tasks
- [ ] Create proposal on how to help prevent non-accessible code from being merged into the code base
- [ ] Create automation to help prevent non-accessible code from being merged into the code base
```

For identified accessibility issues, create tickets and provide a comment on this issue with the discovered accessibility issues, and I will add them to this parent task to track.

**Comment by Pushpajyothi** [comment]
Accessibility Issue for Dashboard :
1. https://github.com/awslabs/iot-app-kit/issues/2123

**Comment by Pushpajyothi** [comment]
Accessibility issues observed in IoT-App-Kit :

1. https://github.com/awslabs/iot-app-kit/issues/2168
2. https://github.com/awslabs/iot-app-kit/issues/2170
3. https://github.com/awslabs/iot-app-kit/issues/2172
4. https://github.com/awslabs/iot-app-kit/issues/2173
5. https://github.com/awslabs/iot-app-kit/issues/2175
