### ISSUE TITLE
Chart fit and finish - Improve chart legend UX

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#1930]
Current charts legend for line chart and scatter chart has large spacing between rows, and margins on the left and right. Want to Update to a more compact UX

UX Notes:

Fixed width for legends, legends text to be wrapped and the user can see the name of the property on-hover, remove the bottom scroll until it is necessary. Add consistent padding around the widget, try with 16px, 20px. Change border of legend table - gray 200, 2px

```[tasklist]
### UX
- [x] Provide specific guidance on desired spacing
```

```[tasklist]
### Engineering
- [ ] Update spacing/layout for legend (pre. req of UX guidance)
```

**Comment by nadeswal** [comment]
UX specs -

No specific px value, however, I'd like the padding to be reduced to either 2px or 4px so we don't take a lot of space between the rows.

Also, make sure we make the text within the field wrapped.
