### ISSUE TITLE
Dashboard: header design update

### ISSUE THREAD

**Issue by nadeswal** [awslabs/iot-app-kit#1947]
This task is to update the dashboard header to contain the dashboard name and other UX improvements details below.

## UX details
<img width="797" alt="header-ux" src="https://github.com/awslabs/iot-app-kit/assets/77755322/a4e30237-9fbb-4599-b005-2a3268061153">

-  Create another dashboard component
-  On the left, add the name of the dashboard, use title header- page component.
- Move time machine and action stripe to the right as shown in the picture above.
- Use grey 900 as bg-color
-  Use h= 80px for the component box
- do not add the "info" link that is shown on the mock.

```[tasklist]
### Acceptance criteria
- [ ] Adheres to provided UX details
- [ ] Is accessible
- [ ] has a snapshot test
```

**Comment by diehbria** [comment]
will reopen once UX is provided

**Comment by nadeswal** [comment]
<img width="1296" alt="Screenshot 2023-10-20 at 2 43 50 PM" src="https://github.com/awslabs/iot-app-kit/assets/141063047/eeb57685-b870-44b4-8189-37c7cc09b3a4">

Updated the header section!

**Comment by gmuralidharreddy** [comment]
> <img alt="Screenshot 2023-10-20 at 2 43 50 PM" width="1296" src="https://user-images.githubusercontent.com/141063047/277025969-eeb57685-b870-44b4-8189-37c7cc09b3a4.png">
> Updated the header section!

@nadeswal @diehbria Can I remove titles for **Time machine** and **Actions**? or keep it as it is?

![image](https://github.com/awslabs/iot-app-kit/assets/139960352/808f3db7-af09-4aa1-ada9-68b132e70b64)

**Comment by nadeswal** [comment]
Yes, please remove it.

**Comment by nadeswal** [comment]
<img width="815" alt="Screenshot 2023-11-29 at 4 32 29 PM" src="https://github.com/awslabs/iot-app-kit/assets/141063047/56492c3e-d40a-4b34-b6c8-c8a52be57b08">

Updated mock
