### ISSUE TITLE
Chart fit and finish - Invalid data styling

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#1952]
There is a display that occurs when an invalid data type is added within a widget, for example - attempting to add string data to a line chart.

This task is to update this styling to the UX provided.
<img width="620" alt="invalid-data" src="https://github.com/awslabs/iot-app-kit/assets/77755322/b2fa096f-267f-4e48-ba09-369ab7c52d9b">

Copy for widgets:
xy-plot (line/scatter/step chart): "$DATA_TYPE is not supported by the xy-plot"
bar-chart: "$DATA_TYPE is not supported by the bar chart"

```[tasklist]
### Acceptance criteria
- [ ] Invalid data types will not be added to a widget upon clicking "add"
- [ ] Resource explorer allows you to select an invalid widget type 
- [ ] Notification appears for every invalid data type that was attempted to be added upon hitting "add" button.
- [ ] charts do not add anything other than numerical data
- [ ] KPI supports all data types
- [ ] Status supports all data types
- [ ] table supports all data types
- [ ] status timeline supports all data types
- [ ] bar chart only supports numerical data
- [ ] when "add" is clicked, all datastreams/properties are de-selected
```

**Comment by diehbria** [comment]
will reopen once we have UX guidance provided within ticket

**Comment by nadeswal** [comment]
**Updated UX guidelines to the ticket -** 

Disable string data type in resource explorer and add alt text "String data not supported for the selected widget."

![tc](https://github.com/awslabs/iot-app-kit/assets/141063047/723201e3-0481-4b03-a701-6e816e0cc3cc)
