### ISSUE TITLE
Dashboard: re-introduce status widget icon

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#1977]
This task is to re-introduce the status widgets icon on the component library portion to enable users to add a status widget onto the dashboard.

Utilize the status icon which was removed within this pull request: https://github.com/awslabs/iot-app-kit/pull/1900/files#diff-2699ff588

![Screenshot 2023-09-26 at 3 43 38 PM](https://github.com/awslabs/iot-app-kit/assets/77755322/ef644996-8f23-46c6-80bc-4dc31e34875b)

```[tasklist]
### Tasks
- [ ] Status icon is added to component library
- [ ] User is able to append a status widget to their dashboard
```

_Note: The motivation for this task is because we have not yet developed an alternative workflow to enable users to add a status widget to their dashboard._

**Comment by nadeswal** [comment]
![status-1](https://github.com/awslabs/iot-app-kit/assets/141063047/859a956d-631f-438a-afd1-b8ccbb0089ba)
![status](https://github.com/awslabs/iot-app-kit/assets/141063047/79f6dd4f-8551-4f79-bc79-ef525c18992b)
