### ISSUE TITLE
Resource explorer: Missing pagination handling for searched model data

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#1994]
Within the IoT App Kit dashboard, the resource explorer on the left side of the dashboard while in edit mode, when a user searches for modeled data streams using the "Search" functionality will incorrectly only display the first 50.

Below is an image of the "search modeled data streams" work flow.

![Screenshot 2023-09-27 at 5 17 31 PM](https://github.com/awslabs/iot-app-kit/assets/77755322/f9a81cb6-014c-4cd3-9ac2-45c3970db39c)

```[tasklist]
### Tasks
- [ ] User is able to search modeled data and view all results when there are more than 50 results returned
- [ ] Test case implemented
```

**Comment by gmuralidharreddy** [comment]
@diehbria can you please record a video for this bug and share it here? I created the Twinmaker workspace and did the setup in my local environment. However, I am unable to get any data from the backend to reproduce/fix the issue.

**Comment by gmuralidharreddy** [comment]
@diehbria can you please check this video which I recorded with dummy data. I think from this ticket based on my understanding it was working fine. there was no pagination issue. please check it and let me know.


https://github.com/awslabs/iot-app-kit/assets/139960352/17788f01-514a-4f70-9f8a-9be6125cf29b

**Comment by diehbria** [comment]
@gmuralidharreddy issue not fixed, sync with @tracy-french to fix
