### ISSUE TITLE
Dashboard - side panel sizing adjustments

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#2046]
**Description:**
This task is to alter the sizing, and sizing behavior of the left and right side panels within the dashboard (resource explorer, and configuration pane)

**Acceptance criteria:**
```[tasklist]
- [ ] configuration panel becomes fixed width, set to 500px
- [ ] resource explorer has a minimum width of 300px, and a max width of 800px
```

**Comment by gmuralidharreddy** [comment]
@nadeswal @diehbria here are a couple of queries for this task:
a. Do we need to remove the resizer for the right-side config panel?
b. What is the default width for the left side resource explorer panel when it is expanded, can make it as same as the right side(500px)?

**Comment by nadeswal** [comment]
I agree with @diehbria
