### ISSUE TITLE
[ResourceExplorer] Make "add" button sticky

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#2114]
# Description:

This task is to make it so that the "add" button on the resource explorer shows, even when there are many results on the page. The method to achieve this will be to make the button "add button" such that it always is visible at the very bottom of the resource explorer.

```[tasklist]
### Acceptance criteria
- [ ] Is accesibile
- [ ] contains a snapshot test
- [ ] adheres to UX detailed in this ticket
```

**Comment by mnischay** [comment]
![Screenshot 2023-11-17 at 12 55 52 PM](https://github.com/awslabs/iot-app-kit/assets/135036199/b143efe9-7dc6-46e9-b127-b8f85e8984e9)
