### ISSUE TITLE
[Dashboard] Opening panels should create a scroll instead of moving widgets

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#2138]
## Description:

When the resource explorer opens, it pushes the dashboard over to the right.

The desired behavior is for the resource explorer to "overlap" the dashboard instead, and provide users the ability to scroll

```[tasklist]
### Acceptance criteria
- [ ] opening and closing resource explorer does not move the dashboard widgets, instead overlaps, with the ability to scroll
```

**Comment by mnischay** [comment]
The Resource explorer will be re-designed shortly or refactored and the this change is a bit more complex than just updating a flag or width... DIscussed with the team and @diehbria , decided to close this for now.
