### ISSUE TITLE
Chart Legend

### ISSUE THREAD

**Issue by jmbuss** [awslabs/iot-app-kit#2277]
This task enables users of the IoT App Kit Chart component in the react-components package to display more information and customize the UX for their chart legends.

# User experience of the configuration panel

## Widget level configuration

Widget level legend configuration for the line widget is found under the “style tab”, under the “Legends” sub section (which does not currently exist).

![Screenshot 2023-12-13 at 4 00 15 PM](https://github.com/awslabs/iot-app-kit/assets/77755322/04982b4f-9638-43fd-b399-94c4a3da0fb5)

This new sub section will include a toggle “View on chart” in the section header, which will determine whether or not the legend is shown in the Chart component. 

**By default this will be enabled and the legend will be visible.**

---

Within the “Legends“ sub section, there will be a dropdown labeled ”Alignment”. 
This dropdown will include 3 options:

1. Right
2. Left
3. Bottom

**Right will be the default option for this dropdown.**

---

Within the “Legends“ sub section there will be a label for ”Display” and checkboxes underneath. There will be checkboxes for “Unit” and “Asset name”. These will determine whether or not datastream _units_ and datastream _asset names_ are displayed within the legend.

**By default both “Unit” and “Asset name” will be checked and displayed in the legend.**

## Implementation Information

In order to support these new configuration options, a change to the dashboard type definition is required.

**File** where change is required - `packages/dashboard/src/customization/widgets/types.ts`

**Type** where change is required - `ChartLegend`

Existing type definition:
```
type ChartLegend = {
  visible?: boolean;
};
```

New type definition:
```
type ChartLegend = {
  visible?: boolean;
  position?: 'left' | 'bottom' | 'right';
  height?: string;
  width?: string;
  visibleContent?: { 
    latestValue?: boolean; // defaults as false
    asset?: boolean; // defaults as false
    unit?: boolean; // defaults as false
  };
};
```

UX to type mapping:
“View on chart” toggle → `visible`
“Alignment”→ `position`
“Display”, “Unit” → `visibleContent.unit`
“Display”, “Asset name” → `visibleContent.asset`
“Display”, “Latest value” → `visibleContent.latestValue`

The xy-plot widget component `packages/dashboard/src/customization/widgets/lineScatterChart/component.tsx` will need to implement a callback `onChartOptionsChange` _(defined below)_ which will update the legend `height` and `width` properties in the dashboard definition.

---

# User experience of the chart component

**Right aligned legend (position: ‘right’)**

![image (13)](https://github.com/awslabs/iot-app-kit/assets/107281089/72bf4a39-806c-47fc-be4d-b3b8e76a9987)

**Left aligned legend (position: ‘left’)**

![image (14)](https://github.com/awslabs/iot-app-kit/assets/107281089/f8cdb7e2-9ff3-4337-b3d2-6d6bbca78c46)

**Bottom aligned legend (position: ‘bottom’)**

![image (15)](https://github.com/awslabs/iot-app-kit/assets/107281089/e77f4fb6-c7d6-4c43-97b8-0cb50e629a54)

## Implementation Information

**Table Component:** 
The legend component should be implemented using [TanStack Table](https://tanstack.com/table/v8)

---

In order to support the new configuration options in the Chart component, a change to the Chart options is required.

**File** where change is required - `packages/react-components/src/components/chart/types.ts`

**Type** where change is required - `ChartLegend`

Existing type definition:

```
type ChartLegend = {
  backgroundColor?: string;
  position?: 'top' | 'bottom';
};
```
New type definition:

```
type ChartLegendContent = 'unit' | 'asset' | 'visibility';
type ChartLegend = {
  visible?: boolean;
  position?: 'left' | 'bottom' | 'right';
  height?: string;
  width?: string;
  visibleContent?: { [key in ChartLegendContent]?: boolean; };
};
```

The legend `width` and `height` should support css absolute units: `px, em, rem`, and relative units: `%`
If no unit is provided after the number, we will use the unit: `px`.

New Chart Options:
```
type ChartOptions = {
  /** existing options */
  onChartOptionsChange?: (options: Omit<ChartOptions, 'queries'>) => void;
};
```

Default Value for onChartOptionsChange:
```
import noop from 'lodash.noop';

const options: ChartOptions = {
   ...existingOptions,
    onChartOptionsChange: noop,
};
```

The `onChartOptionsChange` callback should be triggered any time any of the chart options change from inside the Chart component. This is important for the legend width and height updates.

Default values for ChartLegend:
```
const defaultChartLegend: ChartLegend = {
  visible: true,
  position: 'right',
  width: '30%',
  height: '30%',
  visibleContent: {
    unit: true,
    asset: true,
  },
};
```

## Accessibility Notes 
The table component should follow WCAG 2.2 Level AA standards.

* Rows in the legend table that are hidden will require alt text and an aria-hidden label
* The color icon will need alt text and a tooltip describing the highlight / un-highlight action
* The eye icon will need alt text and a tooltip describing the show / hide action.

**Comment by YadhunandanGowda** [comment]
Hi @jmbuss 

I have implemented the Legend section UI, I'm current working on the functionality part of it.
![Screenshot 2023-11-24 at 12 48 13 PM](https://github.com/awslabs/iot-app-kit/assets/65999096/fd3f3d80-23fc-474f-b33e-949582f5a9cf)

While implementing it I have come across the right legend, which is not mentioned in this issue, so can I get some clarification/input on that?
like what should be the position of the right legend on change of alignment.
![Screenshot at Nov 24 12-55-46](https://github.com/awslabs/iot-app-kit/assets/65999096/54cc1200-fd53-4438-85b2-0b5f4cfdc381)

**Comment by nadeswal** [comment]
See the attached screenshot on how the multiple Y-axis should behave on left alignment of legends. 

<img width="755" alt="Screenshot 2023-11-27 at 11 57 18 AM" src="https://github.com/awslabs/iot-app-kit/assets/141063047/636ae1fc-e822-4db7-8cee-fc41ddf33e76">

**Comment by mnischay** [comment]
![Screenshot 2023-12-27 at 11 12 53 AM](https://github.com/awslabs/iot-app-kit/assets/135036199/64cca7f1-f04f-429f-b65c-7b841dede2d8)

**Comment by mnischay** [comment]
![Screenshot 2023-12-27 at 11 14 18 AM](https://github.com/awslabs/iot-app-kit/assets/135036199/e1412839-0212-402d-8069-a4e41f6ba2ea)
