### ISSUE TITLE
[Dashboard] tabs on config panel present that are unusable 

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#2308]
configuration panel tabs are present for widgets where they have no use

i.e.  thresholds for a text widget

Acceptance criteria:

ensure every widget only has tabs and options which pertain to the given widget

```[tasklist]
### Acceptance criteria
- [ ] for every available widget, tabs are only present that pertain to the respective widget
```

**Comment by mnischay** [comment]
TO BE DONE for status and KPI, but only after adding is not allowed
