### ISSUE TITLE
[Dashboard] add functioning bar chart and status timeline title

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#2312]
Bar chart and status timeline do not correctly expose the ability to title the widgets.

Bar chart and status timeline should have a "title" feature, exactly the same as the "XY-plot" (line chart, scatter chart, etc)

Each respective widget, when the configuration panel is open the first field should be present as shown below (exactly like xy-plot)

<img width="490" alt="Screenshot 2023-11-29 at 7 26 46 AM" src="https://github.com/awslabs/iot-app-kit/assets/77755322/634f886f-9d45-40c1-a2ce-f1ce3eb1a18e">

The default title should be blank.

```[tasklist]
### acceptance criteria
- [ ] bar chart has a functioning title
- [ ] bar chart has no default title
- [ ] status timeline has a functioning title
- [ ] status timeline has no default title
```

**Comment by Chandru-HM** [comment]
Hi @diehbria 

1. do we need to add widget title for KPI, Status and Table widget as well? (currently, showing for line widget, for bar and status timeline added as mentioned in ticket AC)
2. do we need to show title in empty state widget? (currently, not showing in line widget and we have empty state for status timeline, KPI and status widgets as well)

**Comment by diehbria** [comment]
Only worry about whats in the issue (bar chart / xy-ploy / status-timeline)

title should be displayed in empty state
