### ISSUE TITLE
[Accessibility][DashboardToolbar] Headings are not marked up as headings

### ISSUE THREAD

**Issue by mnischay** [awslabs/iot-app-kit#2364]
### Acceptance Criteria

- [ ] The DashboardToolbar Headings are marked up as headings

**Comment by Kausar-HM** [comment]
As per the new header design we moved the time machine and actions to black header and also we removed the titles for them so I think we can close this ticket.
CC @gmuralidharreddy

**Comment by jmbuss** [comment]
Yes, we can close this ticket.
