### ISSUE TITLE
[Widget] panel UX: On-select/hover widget-level actions

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#2439]
This task is to add a on-select and on-hover action state for the widget. This will be applicable for all the widgets.

This task is to update the "widget panel" and how it exposes the delete action.
UPDATE: this should include download button as well (01/19/24)

Currently, the "delete action" is always presents on some widgets while in edit mode.

This task is to change the panel UX so that the "delete" button only displays when a widget is selected or is hovered on while in edit mode.

(Note that the "download" icon won't be part of this implementation)
UPDATE : download button is now available (01/19/24)

UX guidelines - 
![Screenshot 2024-01-03 at 12 47 44 PM](https://github.com/awslabs/iot-app-kit/assets/77755322/6cda634a-d371-4106-ad20-5ba34176c5f5)

- Add a 5px rounded corner radius - 58x24px rectangle (this is as per the designs - feel free to play with the size to match the - design and the widget size which will be relative to the user making it small or large)
- Add 10px padding on both side and in the middle of the icon
- Icon size 14px (buttons should use the cloudscape inline icon button)

```[tasklist]
### Acceptance criteria
- [ ] Update "panel UX" to expose delete on hover/select per UX guidance
- [ ] New panel UX is accessibile
- [ ] Utilize new panel UX for xy-plot
- [ ] Utilize new panel UX for KPI
- [ ] Utilize new panel UX for Status
- [ ] Utilize new panel UX for table
- [ ] Utilize new panel UX for bar chart
- [ ] Utilize new panel UX for status timeline
- [ ] Get UX signoff from UX (Navita Deswal)

```

**Comment by Kausar-HM** [comment]
@mnischay 
We need to update the ticket description to be inclusive of download button as well since now the download button is available in latest rc, it looks like this
![image](https://github.com/awslabs/iot-app-kit/assets/154328164/51abf8c2-8cbe-4470-8932-692a8c49f451)

We are already working on updating the buttons UX

**Comment by gmuralidharreddy** [comment]
@nadeswal
Can you please provide the UX for download icon placement in the preview mode?

**Comment by mnischay** [comment]
@Kausar-HM : @corteggiano  mentioned that `the download button should be disabled when a table kpi or status  is not in live mode`

**Comment by nadeswal** [comment]
### Story continuation --
**View mode:**
The view mode will support the hover state which will enable the user to download the widget.

Refer screenshot -
<img width="510" alt="Screenshot 2024-01-24 at 4 57 16 PM" src="https://github.com/awslabs/iot-app-kit/assets/141063047/81b02c69-e2c2-416b-a1a0-1bc3774f4e30">
