### ISSUE TITLE
widget level config panel UI updates

### ISSUE THREAD

**Issue by mnischay** [awslabs/iot-app-kit#2467]
some of the options do not make sense to be allowed when change when their respective parent option is in a particular state
example: when the legend is turned off, let the user select the other legend options might not be good UX

Below are the such cases we have in the config panel

![Screenshot 2024-01-11 at 1 58 57 PM](https://github.com/awslabs/iot-app-kit/assets/77755322/761366a2-d17c-470f-b194-1212dc5c6499)
![Screenshot 2024-01-11 at 1 58 37 PM](https://github.com/awslabs/iot-app-kit/assets/77755322/25fb245d-c45d-4b1d-8fbc-37dab037928f)

```[tasklist]
### Acceptance Criteria
- [ ] when the legend is hidden the corresponding options should be disabled
- [ ] when the Y-axis is hidden the corresponding options should be disabled

```

**Comment by diehbria** [comment]
will reopen once more details are added
