### ISSUE TITLE
[Dashboard] Grid not scrollable

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#2622]
In `rc` branch, when the dashboard is larger than the window, it is not scrollable. The effect of this is that users cannot view all of their widgets.

```[tasklist]
### Acceptance criteria
- [ ] Dashboard is scrollable
```

**Comment by Chandru-HM** [comment]
Dashboard grid is now scrollable. am not sure when got fixed. please let me know if the issue is still reproducing.
