### ISSUE TITLE
[Widgets] Table Data Quality

### ISSUE THREAD

**Issue by jmbuss** [awslabs/iot-app-kit#2664]
This task is to add data quality indicators to the table component. - `packages/react-components/src/components/table`

UX for Uncertain data
![image](https://github.com/awslabs/iot-app-kit/assets/107281089/8eae181a-8c01-4d25-ab43-687bd3fc64ee)

`DataPoint` has a new property called `quality`. If the `quality` is "BAD" or "UNCERTAIN", we want to show an icon and text next to the value like in the image above.

### Acceptance Criteria
**Bad Quality**
Show the text "Bad Quality" as red with an Icon from cloudscape.
The icon should be the status-negative name with error variant.
`<Icon name="status-negative" variant="error" /> Bad Quality`

**Uncertain Quality**
Show the text "Uncertain Quality" as yellow with an Icon from cloudscape.
The icon should be the status-warning name with warning variant.
`<Icon name="status-warning" variant="warning" /> Uncertain Quality`

**Comment by Kausar-HM** [comment]
@jmbuss 
I could not find a way to access the property "quality" like other properties in table after debugging the flow from `packages/dashboard/src/customization/widgets/table/component.tsx`

I traced this location where other data is returned
![image](https://github.com/awslabs/iot-app-kit/assets/154328164/6c8e0613-ad54-49f9-90c0-f61926d01bd7)

The `queries` does not have the quality property, could you please suggest the approach to make it available here?

**Comment by jmbuss** [comment]
The quality is on the data point object. you will be able to see it in this file - `packages/react-components/src/components/table/createTableItems.ts`

it's accessible on `datastream.data[number].quality`
