### ISSUE TITLE
Please update README file for TwinMaker scene viewer

### ISSUE THREAD

**Issue by YusakuNo1** [awslabs/iot-app-kit#273]
Hey guys, please update the [image](https://user-images.githubusercontent.com/6397726/159107236-ea95e7ba-a89c-43e6-a34c-c5ea1dd37e8b.png) in README file, it didn't show TwinMaker scene viewer there :p

@sheilaXu @TheEvilDev

**Comment by diehbria** [comment]
closing as stale
