### ISSUE TITLE
RefreshRate Error Misspelling

### ISSUE THREAD

**Issue by steve-carpenter** [awslabs/iot-app-kit#2777]
**Describe the issue with documentation**
Misspelling in [error message ](https://github.com/awslabs/iot-app-kit/blob/ce10aba15c135384cba66f018fb2f502aac1d4eb/packages/core/src/data-module/subscription-store/refreshRate.ts#L19)

_Error: Refresh rate has minimum value of 1000 miliseconds. Setting rerfesh rate to 1 second._

**Comment by corteggiano** [comment]
Thank you for the report! we've fixed this and it will be fixed in the next version of iot-app-kit

**Comment by diehbria** [comment]
closing as issue has been fixed and released. Thank you for reporting this misspelling!
