### ISSUE TITLE
SceneViewer "TypeError: Cannot read properties of undefined (reading 'primaries')"

### ISSUE THREAD

**Issue by amy-nihao** [awslabs/iot-app-kit#2915]
**Describe the bug**
When attempting to view a Twinmaker scene with `SceneViewer` in a React app I receive the following error:
```
TypeError: Cannot read properties of undefined (reading 'primaries')
    at Object.getPrimaries (three.module.js:1702:1)
    at uploadTexture (three.module.js:24498:1)
    at WebGLTextures.setTexture2D (three.module.js:24269:1)
    ...
```

**To Reproduce**
1. Install packages `@iot-app-kit/source-iottwinmaker` and `@iot-app-kit/scene-composer`
2. Create an AWS Twinmaker workspace with a scene
3. Add a .glb model to the scene
4. Create sceneloader with `const sceneLoader = initialize('workspace', { client }).s3SceneLoader('scene')` and appropriate workspace and scene ids
5. Return <SceneViewer sceneLoader={sceneLoader}/> as a component
6. Run app and see error

**Expected behavior**
Code compile correctly and web app show the 3d scene with the glb model

**Screenshots**
![Screenshot 2024-07-11 at 10 38 00 AM](https://github.com/awslabs/iot-app-kit/assets/66326903/b60b6bda-5b08-4b5d-a08f-7d35586ea662)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Additional context**
I tried with my own workspace scene as well as a test scene with a simple cube .glb, both produced the same error

**Comment by diehbria** [comment]
Thanks for reaching out, I'll bring this to the teams attention to get back to you shortly with an update

**Comment by mitchlee-amzn** [comment]
There is likely an issue with how you are initializing the datasource. You can checkout the example app in `examples/react-app` for some clues, but essentially you can look at [the datasource configuration](https://github.com/awslabs/iot-app-kit/blob/main/examples/react-app/src/dataSource.ts) as a reference guide, as well as the [scene viewer wrapper](https://github.com/awslabs/iot-app-kit/blob/main/examples/react-app/src/components/SceneViewer.tsx) for all the properties that need to be provided for it to run.

The scene viewer data source provides both the s3SceneLoader and the sceneMetadataModule that is necessary to initialize an instance of the Scene Viewer.

**Comment by chejimmy** [comment]
Issue should be fixed by previous comment.
Feel free to reopen if further assistance is needed 🙏
