### ISSUE TITLE
Scene composer tests reference invalid import from THREE.JS

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#754]
Invalid referrences to `THREE.RGBFormat`,

i.e.

```
    const texture = new THREE.DataTexture(new Uint8Array(3), 2, 2, THREE.RGBFormat);
```

https://github.com/awslabs/iot-app-kit/pull/753/files#diff-35941ce23754ca222a3e917e934328bfe3de76124f775cdd7c9ca598f9dad631R93

In version 137, RGB has been deprecated in favor of RGBAFormat: https://github.com/mrdoob/three.js/wiki/Migration-Guide#136--137

**Comment by TheEvilDev** [comment]
This has been merged.
