### ISSUE TITLE
VideoJS dependency of VideoPlayer redefines global/document and globalwindow

### ISSUE THREAD

**Issue by diehbria** [awslabs/iot-app-kit#775]
The VideoPlayer component have a dependency `video.js` has a long standing issue where `global/document` and `global/window` get redefined for their internal testing, which causes users of the package who also have code that rely on these standard global variables to use complicated work-arounds to have their code bases work.

https://github.com/videojs/video.js/issues/5680 for context

This issue was fixed in https://github.com/videojs/video.js/pull/6954, but when the `VideoPlayer` is exported from `react-components`, a basic usage within storybook results in the following error:

```
 ERR! ModuleNotFoundError: Module not found: Error: Can't resolve 'global/window' 
```

If i remove `VideoPlayer` from being exported, this issue goes away which is why I am confident video.js is the root cause.

## Expected behavior
I should be able to import in `VideoPlayer` and not have to write shims to get the library imported in projects that utilize `global/document` and `global/window`

**Comment by mumanity** [comment]
Looking into this.

**Comment by mumanity** [comment]
This should be resolved.
