### ISSUE TITLE
Type checking error on `comparisonOperator` in annotations

### ISSUE THREAD

**Issue by sudhirjena** [awslabs/iot-app-kit#83]
**Describe the bug**
Can't build ReactJS Typescript project because of the following type checking error

**Code**
```
{/* --- BEGIN: `StatusTimeline` implementation*/}
<StatusTimeline
    viewport={{ duration: '15m' }}
    annotations={{ 
        y: [
            { color: '#FF0000', comparisonOperator: 'EQ', value: 30.45 },
            { color: '#0000FF', comparisonOperator: 'EQ', value: 2.93 },
            { color: '#00FF00', comparisonOperator: 'EQ', value: 2.93 },
        ] 
    }}
    queries={[
        query.timeSeriesData({
            assets: [{
                assetId: props.assetId,
                properties: [{
                    propertyId: props.propertyId
                }]
            }]
        })
    ]}
/>
<WebglContext/>
{/* --- END: `StatusTimeline` implementation*/}
```

**Error**
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/1389495/156849558-26e70eb6-bf0c-4e48-9c33-74ea723713fd.png">

**To Reproduce**
1. Try implementing annotations in `StatusTimeline` component in ReactJS Typescript project 
2. See error
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/1389495/156849558-26e70eb6-bf0c-4e48-9c33-74ea723713fd.png">

**Expected behavior**
Type check should be successful

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 98.0.4758.109 (Official Build) (x86_64)

**Additional context**

**Comment by NorbertNader** [comment]
Thank you for creating this issue @sudhirjena !

Looks like we have to use the `COMPARISON_OPERATOR` enum from [@awslabs/synchro-](https://github.com/awslabs/synchro-charts)

```
import { COMPARISON_OPERATOR } from '@synchro-charts/core';
...
<StatusTimeline
    ...
    annotations={{ y: [
    {
       ...
        comparisonOperator: COMPARISON_OPERATOR.GREATER_THAN,
     },
    ] }}
/>
```
