### ISSUE TITLE
Pagination size in `IotResourceExplorer` or `ResourceExplorer` should be configurable

### ISSUE THREAD

**Issue by sudhirjena** [awslabs/iot-app-kit#84]
**Is your feature request related to a problem? Please describe.**
I want to display my sitewise assets in pages of size 10 as I have multiple production lines each containing 10 numbered assets. Displaying 20 assets by default leads to confusion among operators.

**Describe the solution you'd like**
I wish that an optional prop be introduced for `IotResourceExplorer` or `ResourceExplorer` with which I can define the page size when I pass `paginationEnabled={true}`. This is currently blocked by a hardcoded `pageSize` shown below from https://github.com/awslabs/iot-app-kit/blob/3da4a1ba644756d9bf47f6ad5df0567dcadc644d/packages/components/src/components/iot-resource-explorer/iot-resource-explorer.tsx#L119

```
if (this.paginationEnabled) {
    collectionOptions.pagination = { pageSize: 20 };
  }
```

**Describe alternatives you've considered**

I do not see any viable alternatives as of now.

**Additional context**

**Comment by NorbertNader** [comment]
Thank you for opening this issue @sudhirjena ! I think that is would be a great feature, we will consider this and I will get back to you asap. If you feel like you would want to contribute, please feel free to submit a PR.
