### ISSUE TITLE
Support for ES6 import declaration of `@iot-app-kit/components/loader`

### ISSUE THREAD

**Issue by sudhirjena** [awslabs/iot-app-kit#88]
**Is your feature request related to a problem? Please describe.**
Currently a ReactJS app built with @iot-app-kit doesn't work when using ES6 style imports of `@iot-app-kit/components/loader`

```
...
import { defineCustomElements } from "@iot-app-kit/components/loader";
...
```

Because of the above missing feature we have to rely on ES5 style imports
```
...
const { defineCustomElements } = require("@iot-app-kit/components/loader");
...
```

**Describe the solution you'd like**
We would like ES6 style imports for `@iot-app-kit/components/loader` to be supported i.e.,
```
import { defineCustomElements } from "@iot-app-kit/components/loader";
```
should be natively supported.

**Describe alternatives you've considered**
The only other available alternative is ES5 style imports as mentioned above.

**Additional context**

**Comment by boweihan** [comment]
Hi @sudhirjena, thanks for raising this issue. May I ask why you need to import `defineCustomElements` to use app kit components in a React project? If possible, please use our exported React components directly, e.g. `import { LineChart } from '@iot-app-kit/react-components'`.

**Comment by diehbria** [comment]
Moving towards only supporting react components, so closing out this issue
