### ISSUE TITLE
Support ability to pre-filter asset ids before initial render in `ResourceExplorer`

### ISSUE THREAD

**Issue by sudhirjena** [awslabs/iot-app-kit#89]
**Is your feature request related to a problem? Please describe.**
Resource explorer should support props for filtering a list of sitewise asset ids without relying on any relation to sitewise hierarchy trees. Consider the situation where a customer is building a dashboard for selected sitewise assets only from a large list of many assets they have in sitewise. Since, the customer would like to focus on limited assets for the custom dashboard, they don't want to display all sitewise assets by default when they use:
```
...
<ResourceExplorer
    query={query.assetTree.fromRoot()}
    columnDefinitions={columnDefinitions}
/>
...
```

**Describe the solution you'd like**
* If this is currently possible, [documentation](https://github.com/awslabs/iot-app-kit/blob/main/docs/ResourceExplorer.md) should be improved demonstrating how to pre-filter matching asset ids on initial render.
* If this is currently **not** possible, then a prop should be provided in `ResourceExplorer` component to pre-filter matching asset ids and display only matching assets on initial render.

**Describe alternatives you've considered**
There are no documented alternatives as of now. All sitewise assets are displayed by default when using `query.assetTree.fromRoot()`.

**Additional context**

**Comment by boweihan** [comment]
Hi @sudhirjena, thanks for raising this feature request. The documentation for asset tree queries is [here](https://github.com/awslabs/iot-app-kit/blob/main/docs/AWSIoTSiteWiseSource.md#assettree) and currently we don't support pre-filter criteria on queried assets. What type of asset filtering criteria did you have in mind?
