### ISSUE TITLE
Twinmaker Sceneviewer integration

### ISSUE THREAD

**Issue by rakshitha2209** [awslabs/iot-app-kit#909]
**Describe the issue with documentation**
A clear and concise description of what the issue is.
How to integrate the twinmaker into the appkit?

 
![image](https://user-images.githubusercontent.com/57610741/230390272-b5b97e29-07a1-4a69-b0b0-b693799ce338.png)

I tried this method, I am not able to render the twinmaker in the dashboard.

Can you provide a more precise code as to how to actually render the twinmaker scene.

**Comment by MO-Elmu** [comment]
We have a detailed full react example [here](https://github.com/awslabs/iot-app-kit/tree/main/examples/react-app). In general to load a Scene in a SceneViewer in your dashboard this assumes you already created a TwinMaker workspace and composed a scene in that workspace using Scene Composer in AWS TwinMaker Console. Then you provide all these info like AWS account credentials (account where your workspace is created), region, workspace Id, scene Id and any queries related to scene rules see [config](https://github.com/awslabs/iot-app-kit/blob/main/examples/react-app/src/configs.ts) file in the example mentioned above.
